name: maharah_project
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk:
      flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/image/

  fonts:

    - family: primaryFont
      fonts:
        - asset: assets/font/a-jannat-lt-bold.ttf
        - asset: assets/font/a-jannat-lt.ttf
          weight: 700